# Generated by Django 5.2.16 on 2026-08-15 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAttendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginlogoutlog',
            name='action',
            field=models.CharField(choices=[('Login', 'Login'), ('Logout', 'Logout')], max_length=10),
        ),
    ]
