# Generated by Django 5.2.16 on 2026-08-15 22:37

import UserAttendance.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAttendance', '0002_alter_loginlogoutlog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='userattendance',
            name='out_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userattendance',
            name='out_image',
            field=models.ImageField(blank=True, null=True, upload_to=UserAttendance.models.attendance_out_image_path),
        ),
        migrations.AddField(
            model_name='userattendance',
            name='out_latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='userattendance',
            name='out_location',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userattendance',
            name='out_longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
    ]
