# Generated by Django 5.2.16 on 2026-08-16 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAttendance', '0003_userattendance_out_at_userattendance_out_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userattendance',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='userattendance',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='userattendance',
            name='out_latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='userattendance',
            name='out_longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=12, null=True),
        ),
    ]
