# Generated by Django 5.2.9 on 2026-02-12 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0004_message_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='chat_photos/'),
        ),
    ]
